/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package Vista;

import Modelo.ColaLenta;
import Modelo.Consumidor;
import Modelo.Productor;
import java.awt.Color;

/**
 *
 * @author juald
 */
public class ColaFrame extends java.awt.Frame {

    /**
     * Creates new form ColaFrame
     */
    public ColaFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    public static void main(String args[]) throws InterruptedException {
        CanvasCola canvas = new CanvasCola(10);
        ColaLenta cola = new ColaLenta(10, canvas);
        ColaFrame ventana = new ColaFrame();

        ventana.setSize(1024, 768);
        ventana.setBackground(Color.LIGHT_GRAY);

        ventana.add(canvas);
        ventana.setVisible(true);

        Thread hilo1 = new Thread(new Productor(cola));
        Thread hilo4 = new Thread(new Productor(cola));
        Thread hilo2 = new Thread(new Consumidor(cola));

        hilo1.start();
        hilo2.start();
        hilo4.start();

        try {
            hilo1.join();
            hilo2.join();
            hilo4.join();

        } catch (InterruptedException ex) {
            System.out.println("Capturada excepcion de join " + ex.getMessage());
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
